export const UPDATE_CALCULATION_AND_RESULT = "UPDATE_CALCULATION_AND_RESULT";
export const CLEAR_ALL = "CLEAR_ALL";
export const ON_EQUAL_PRESS_UPDATE_CALCULATION_AND_RESULT =
  "ON_EQUAL_PRESS_UPDATE_CALCULATION_AND_RESULT";
export const UPDATE_ON_CLICK_SHIFT = "UPDATE_ON_CLICK_SHIFT";
